spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/knowBlog
    username: bobo
    password: liyanjia
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql





