server:
  servlet:
    context-path: '/blog'
  tomcat:
    max-swallow-size: 100MB

spring:
  profiles:
    active: common,data

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
